# Generated by Django 3.2.8 on 2022-01-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_prediction_ignore_committed'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='collection',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
