version: '3'
services:
  django: &django
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:.
    expose:
      - "8000"
    platform: linux/x86_64
  redis:
    image: redis
    ports:
    - "6379:6379"
  celery-worker:
    <<: *django
    depends_on:
      - redis
    command: ['celery', '-A', 'ml_dashboard', 'worker', '-l', 'info']
  celery-beat:
    <<: *django
    depends_on:
      - redis
      - celery-worker
    command: ['celery', '-A', 'ml_dashboard', 'beat', '-l', 'info']
  