version: '3'
services:
  django: &django
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MIGRATE: ${MIGRATE}
    volumes: 
      - .:.
    expose:
      - "${DJANGO_PORT}"
    platform: linux/x86_64
  redis:
    image: redis
    ports:
    - "${REDIS_PORT}:${REDIS_PORT}"
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:.
    depends_on:
      - redis
    command: ['celery', '-A', 'ml_dashboard', 'worker', '-l', '${LOG_LEVEL}']
    platform: linux/x86_64
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:.
    depends_on:
      - redis
      - celery-worker
    command: ['celery', '-A', 'ml_dashboard', 'beat', '-l', '${LOG_LEVEL}']
    platform: linux/x86_64
  