# Generated by Django 3.2.8 on 2021-11-03 05:08

from django.db import migrations, models
import django.db.models.deletion
import labeling.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[labeling.models.validate_dataset_name])),
                ('created', labeling.models.IntegerDatetimeField(default=0, verbose_name='date created at')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('session', models.IntegerField(default=0)),
                ('collection', models.IntegerField(default=0, null=True)),
                ('mode', models.CharField(blank=True, choices=[('NER', 'Ner'), ('TEXTCAT', 'Textcat'), ('textcat_multilabel', 'Textcat Multilabel')], default='NER', max_length=50, null=True)),
            ],
            options={
                'db_table': 'dataset',
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_hash', models.IntegerField()),
                ('task_hash', models.IntegerField()),
                ('content', models.BinaryField()),
            ],
            options={
                'db_table': 'example',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='labeling.dataset')),
                ('example', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='labeling.example')),
            ],
            options={
                'db_table': 'link',
            },
        ),
    ]
