# Generated by Django 3.2.10 on 2022-01-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='content',
            field=models.JSONField(),
        ),
    ]
