# Generated by Django 3.2.8 on 2021-10-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collections',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcategories',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcategorychildren',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcategorycollections',
            options={},
        ),
    ]
