# Generated by Django 3.2.8 on 2021-10-13 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20211012_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collections',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productcategories',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productcategorychildren',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productcategorycollections',
            options={'managed': False},
        ),
    ]
