# Generated by Django 3.2.8 on 2021-10-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20211013_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('media_logo', models.CharField(max_length=255)),
                ('media_banner', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=45, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'outlets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutletStorefronts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('orders', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'outlet_storefronts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('weight', models.IntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('is_wholesale', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('is_deleted', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'managed': False, 'ordering': ['name']},
        ),
    ]
