# Generated by Django 3.2.8 on 2021-11-03 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_results', '0010_remove_duplicate_indices'),
        ('labeling', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recipe', models.CharField(choices=[('ner.manual', 'Ner Manual'), ('ner.correct', 'Ner Correct'), ('ner.teach', 'Ner Teach')], max_length=40)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('port', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='labeling.dataset')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult')),
            ],
            options={
                'db_table': 'session',
            },
        ),
    ]
