# Generated by Django 3.2.8 on 2021-10-18 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labeling', '0001_initial'),
        ('django_celery_results', '0010_remove_duplicate_indices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recipe', models.CharField(max_length=40)),
                ('command', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Disabled', 'Disabled')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='labeling.dataset')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult')),
            ],
            options={
                'db_table': 'session',
            },
        ),
    ]
