# Generated by Django 3.2.8 on 2021-10-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='port',
            field=models.IntegerField(null=True),
        ),
    ]
