# Generated by Django 3.2.8 on 2021-10-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_session_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='status',
        ),
        migrations.AlterField(
            model_name='session',
            name='port',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
