# Generated by Django 3.2.8 on 2021-10-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20211021_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='command',
        ),
        migrations.AddField(
            model_name='session',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='session',
            name='recipe',
            field=models.CharField(choices=[('ner.manual', 'Ner Manual'), ('ner.correct', 'Ner Correct'), ('ner.teach', 'Ner Teach')], max_length=40),
        ),
    ]
