# Generated by Django 3.2.8 on 2021-10-29 03:29

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0010_remove_duplicate_indices'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('tasks', '0005_alter_session_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Model Tags')),
            ],
            options={
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_meta', models.JSONField(blank=True, default=dict)),
                ('train_meta', models.JSONField(blank=True, default=dict)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.model')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult')),
            ],
            options={
                'db_table': 'trains',
            },
        ),
    ]
