# Generated by Django 3.2.8 on 2021-11-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_train_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='path',
            field=models.CharField(default='test_model', max_length=100),
            preserve_default=False,
        ),
    ]
