# Generated by Django 3.2.8 on 2021-11-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_model_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='mode',
            field=models.CharField(blank=True, choices=[('NER', 'Ner'), ('TEXTCAT', 'Textcat'), ('TEXTCAT_EXCLUSIVE', 'Textcat Exclusive')], default='NER', max_length=50, null=True),
        ),
    ]
