# Generated by Django 3.2.8 on 2021-11-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_model_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='mode',
            field=models.CharField(blank=True, choices=[('NER', 'Ner'), ('TEXTCAT', 'Textcat'), ('textcat_multilabel', 'Textcat Multilabel')], default='NER', max_length=50, null=True),
        ),
    ]
