# Generated by Django 3.2.8 on 2021-11-03 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_model_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
