# Generated by Django 3.2.8 on 2021-11-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_train_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='name',
            field=models.CharField(default='train test', max_length=200),
            preserve_default=False,
        ),
    ]
