# Generated by Django 3.2.8 on 2021-11-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_train_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='train',
            name='model',
        ),
        migrations.RemoveField(
            model_name='train',
            name='task',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
